// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage":return img`
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccc1cccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccc
ccccccccccccccccccccccc1ccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1ccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccc1ccc
ccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccc1cccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccc
cccccccccccccccccccccccccccc1cccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccc1ccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1cccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccc
ccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccc1cccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccc
cccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccc1ccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccc1cccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccc1ccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccc
ccc1cccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccc
cccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccc1ccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccc1cccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccc1ccccccccccc1ccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccc1ccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccc1cccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccc
cccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccc
ccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccc1cccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccc1ccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccc1ccc
cccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cc1ccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccc1ccc
ccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cc1ccccccccccccccccccccccccc1cccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccc1ccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccc
ccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccc1ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccc1ccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1c
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc1cccccccccccccccccccccccccc
`;
            case "image3":
            case "ball":return img`
. . . . . . . . . . . . . . . . 
. . . . . e e e e e e . . . . . 
. . . c e e 2 2 2 2 2 2 . . . . 
. . c e 2 2 2 2 2 2 2 2 2 . . . 
. c e 2 2 2 2 2 2 1 1 2 2 2 . . 
. c e 2 2 2 2 2 2 2 2 1 2 2 . . 
. c e 2 2 2 2 2 2 2 2 1 2 2 . . 
. c e 2 2 2 2 2 2 2 2 2 2 2 . . 
. c e 2 2 2 2 2 2 2 2 2 2 2 . . 
. c e 2 2 2 2 2 2 2 2 2 2 2 . . 
. . e 2 2 2 2 2 2 2 2 2 2 2 . . 
. . c e 2 2 2 2 2 2 2 2 c . . . 
. . . c e 2 2 2 2 2 2 c . . . . 
. . . . . c c c c c c . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "Alien":return img`
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................................................
............................9999............................
..........................99999999..........................
........................999999999999........................
.......................99999991119999.......................
......................9999999991111999......................
......................9999999999911999......................
.....................99999999999991199......................
.....................999999999999999999.....................
....................6999999999999999999.....................
.................bbb6999999999999999999333..................
...............bbbbb6999999999999999999bbb33................
..............bbbbbb6699999999999999996bbbb33...............
............bbbbbbbbb6669999999999996bbbbbbb3333............
..........3bbbbbbbbbbbb669999999996bbbbbbbbbbbb333..........
..........3bbbbbbbbbbbbb6666666666bbbbbbbbbbbbb333..........
..........333bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb33333..........
..........cc33bbbbbbbbbbbbbbbbbbbbbbbbbbbb333333............
............cc33bbbbbbbbbbbbbbbbbbbbbbbb333333c.............
..............cc3333bbbbbbbbbbbbbbbbb3333333c...............
................ccc3333bbbbbbbbbbb333333ccc.................
...................ccc3333333333333333cc....................
.....................ccc333333333333cc......................
.......................ccccccccccccc........................
.......................47dd55555554.........................
......................47dd5555555574........................
......................47d55555555574........................
.....................47d5555555555d74.......................
.....................47d5555555555574.......................
....................47d755555555555d74......................
....................47d555555555555574......................
....................4d75555555555555d74.....................
...................47d55555555555555d74.....................
...................47d555555555555555d74....................
..................47d5555555555555555574....................
..................47d55555555555555555d74...................
.................47d555555555555555555d74...................
.................47d5555555555555555555d74..................
................47d55555555555555555555574..................
................47d555555555555555555555d74.................
...............47d5555555555555555555555d74.................
...............47d55555555555555555555555d74................
...............4d555555555555555555555555d74................
..............47d5555555555555555555555555d74...............
..............4755555555555555555555555555d74...............
.............47d55555555555555555555555555574...............
.............47d555555555555555555555555555d74..............
............47d5555555555555555555555555555d74..............
............47d55555555555555555555555555555d74.............
...........47d555555555555555555555555555555d74.............
...........47d5555555555555555555555555555555d74............
..........47d55555555555555555555555555555555d74............
..........47d555555555555555555555555555555555d74...........
.........47d5555555555555555555555555555555555d74...........
.........47d55555555555555555555555555555555555d74..........
.........4dd55555555555555555555555555555555555574..........
........47d5555555555555555555555555555555555555574.........
........47d5555555555555555555555555555555555555574.........
.......47d555555555555555555555555555555555555555d74........
.......47d555555555555555555555555555555555555555d74........
......47d75555555555555555555555555555555555555555d74.......
......4dd55555555555555555555555555555555555555555d74.......
......4dd555555555555555555555555555555555555555555dd4......
......4dd5555555555555555555555555555555555555555555d4......
......4dd5555555555555555555555555555555555555555555d4......
......47d555555555555555555555555555555555555555555554......
`;
            case "image8":
            case "Dog1":return img`
.................................
.................................
.ee..........ee..................
.eee........eee..................
.e3ee......ee3e..................
.e34e......e43e..................
.e34eeeeeeee43e..................
.e444444444444e..................
.e444444444444e..................
.e441f444441f4e..................
.e44ff44144ff4e.........eeeeee...
.e444441114444e........ee4444ee..
.e444111f11144e.......ee444444e..
.e44411fff1144e.......e4411144ee.
.e444e11111e44e.......e41111144e.
.e4444ee3ee444e.......ed1ed1114e.
.e44444e3e444ee.......eedeed144e.
.e44444eee444ee........eeee1444e.
.e444411144444eeeeeeeeee444444ee.
.e444111114444444444444444444ee..
.e441111111444444444444444444e...
.e441111111444444444444444444e...
.e441111111144444444444444444e...
.e441111111144444444444444444e...
.e441111111e44444444444444444e...
.f44111111ee44444444444444444e...
.fee111111e444444411111444444e...
..fee11111e444444111111144444e...
..ffeee111e4444eeeeeeeeeee444e...
...fffefffe444eeffffeeeffe444e...
.....fef..e44ee....ffeef.e444e...
.....fef..e4ee......feef.ee44ee..
.....fef..e4e........fef..ee44e..
.....fef..e4e........fef...ee4e..
.....fef..e4e.......ffef....e4e..
....ffef..e4e.......feef....e4e..
....feef.ee4e.......ffff...ee4e..
....ffff.e44e..............e44e..
.........eeee..............eeee..
.................................
`;
            case "image12":
            case "Criminal":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....................ffffffffff....................
..................ffffffffffffff..................
.................ffffffffffffffff.................
................ffffffffffffffffff................
...............ffffffffffffffffffff...............
...............ffffffffffffffffffff...............
...............ffffff4444444fffffff...............
...............fff4444444444444ffff...............
...............ff444444444444444fff...............
...............f444444444444444444f...............
................44ffffff44ffffff44................
................4441fff44441fff444................
................444ffff4444ffff444................
................444444444444444444................
................444444444444444444................
.................44444ffffff44444.................
.................4444444444444444.................
...................444444444444...................
.....................44444444.....................
.....................11111111.....................
..................ffffffffffffff..................
...............111ffffffffffffff111...............
...............ffff111111111111ffff...............
....fffffff4...1111ffffffffffff1111...............
......fffff41..fff.111111111111.fff...............
.........f441f.111.ffffffffffff.111...............
...........11f1fff.111111111111.fff...............
............ff1111.ffffffffffff.111...............
.............11fff.111111111111.fff...............
..............f111.ffffffffffff.111...............
...................111111111111.fff...............
...................ffffffffffff.111...............
...................ffffffffffff.fff...............
...................ffffffffffff.444...............
....................ffff..ffff....................
....................ffff..ffff....................
....................ffff..ffff....................
....................ffff..ffff....................
..................ffffff..ffffff..................
..................ffffff..ffffff..................
..................................................
`;
            case "image14":
            case "Criminal0":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
....................ffffffffff....................
..................ffffffffffffff..................
.................ffffffffffffffff.................
................ffffffffffffffffff................
...............ffffffffffffffffffff...............
...............ffffffffffffffffffff...............
...............fffffff4444444ffffff...............
...............ffff4444444444444fff...............
...............fff444444444444444ff...............
...............f444444444444444444f...............
................44ffffff44ffffff44................
................444fff14444fff1444................
................444ffff4444ffff444................
................444444444444444444................
................444444444444444444................
.................44444ffffff44444.................
.................4444444444444444.................
...................444444444444...................
.....................44444444.....................
.....................11111111.....................
..................ffffffffffffff..................
...............111ffffffffffffff111...............
...............ffff111111111111ffff...............
...............1111ffffffffffff1111...4fffffff....
...............fff.111111111111.fff..14fffff......
...............111.ffffffffffff.111.f144f.........
...............fff.111111111111.fff1f11...........
...............111.ffffffffffff.1111ff............
...............fff.111111111111.fff11.............
...............111.ffffffffffff.111f..............
...............fff.111111111111...................
...............111.ffffffffffff...................
...............fff.ffffffffffff...................
...............444.ffffffffffff...................
....................ffff..ffff....................
....................ffff..ffff....................
....................ffff..ffff....................
....................ffff..ffff....................
..................ffffff..ffffff..................
..................ffffff..ffffff..................
..................................................
`;
            case "image16":
            case "John Weak0":return img`
........................................
........................................
........................................
........................................
........................................
........................................
................fffffffff...............
..............fffffffffffff.............
............fffffffffffffffff...........
............fffffffffffffffff...........
............ffeeeeefffeeeeeff...........
............ffefffeefeefffeff...........
............ffeeeffeeeffeeeff...........
............efeeeeeeeeeeeeefe...........
............efeeffeeeeeffeefe...........
............efee1feeeee1feefe...........
............efeeeeeeeeeeeeefe...........
............ffeeeeefffeeeeeff...........
............ffeeeefeeefeeeeff...........
............ffeeeefefefeeeeff...........
.............fffffffffffffff............
..................eeeee.................
...............fff11f11fff..............
.............ffffff1f1ffffff............
.............ffffff1f1ffffff............
.............ffffff1f1ffffff............
.............ffffff1f1ffffff............
.............ff.fff1f1fff.ff............
.............ff.fff111fff.ff............
.............ff.fffffffff.ff............
.............ff.fffffffff.ff............
.............ff.fffffffff.ff............
.............ee.fffffffff.ee............
................fff...fff...............
................fff...fff...............
................fff...fff...............
................fff...fff...............
...............ffff...ffff..............
..............fffff...fffff.............
........................................
`;
            case "image15":
            case "Neighbour0":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.........................................b........
.........................................bb.......
.........................................bb.......
.....................44444444............bbb......
...................444444444444..........b1bb.....
.................4444444444444444........bb1b.....
...............ee44ff44444444ff44ee......bb1bb....
...............ee444fff4444fff444ee......bbb1b....
...............ee4444fff44fff4444ee......bbb1bb...
...............ee4444444444444444ee......bbbbbb...
...............ee444f16644f166444ee......bbbbbb...
................e444f6ff44f6ff444e.......bbbbbb...
................e444ffff44ffff444e.......bbbbbb...
................e4444444444444444e.......bbbbbb...
................e4444444444444444e.......bbbbbb...
................e4444444444444444e.......bbbbbb...
................ee44444444444444ee.......bbbbbc...
.................eeeeeeffffeeeeee........bbbbbc...
.................eeeeeffeeffeeeee........bbbbc....
...................eeeeeeeeeeee..........bbbbc....
.....................44444444............bbbc.....
.....................11111111............bbc......
..................aa88aaaaaa88aa........fbbc......
...............aaaaa88aaaaaa88aaaaa.....ffff......
...............aaaaa88aaaaaa88aaaaa.....fff.......
...............aaaaa8888888888aaaaa...44ff........
...............aaaca8888888888acaaa..aa44.........
...............aaaca8888888888acaaa.aaa44.........
...............aaa.a8888888888accaaaaac...........
...............aaa.a8888888888a.caaaac............
...............aaa.a8888888888a.caaac.............
...............aaa.888888888888.cccc..............
...............aaa.888888888888...................
...............444.888888888888...................
...................888888888888...................
...................888888888888...................
.....................888..888.....................
.....................888..888.....................
.....................888..888.....................
...................88888..88888...................
...................88888..88888...................
..................................................
..................................................
`;
            case "image11":
            case "collar":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . a a a a a a a a . . . . 
. . . a c c c c c c c c a . . . 
. . a c c . . . . . . c c a . . 
. . a a . . . . . . . . a a . . 
. . c a a . . . . . . a a c . . 
. . c c a a a a a a a a c c . . 
. . . c a a a a a a a a c . . . 
. . . . c c c c c c c c . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "Dog2":return img`
.........................
......eee.......eee......
.....ee4ee.....ee4ee.....
.....e444e.....e444e.....
.....e434eeeeeee434e.....
.....e4344444444434e.....
.....e4444444444444e.....
.....e444f1444f1444e.....
.....ee44ff444ff44ee.....
......e44444444444e......
......e4441fff1444e......
.......e4411f1144e.......
........e4411144e........
.........e44444e.........
.........ee444ee.........
........ee44444ee........
.......ee4441444ee.......
.......e444111444e.......
.......e441111144e.......
.......e4e11111e4e.......
.......e4e11111e4e.......
......ee4e1e1e1e4ee......
......e44e1e1e1e44e......
......eeee1eee1eeee......
.........eee.eee.........
`;
            case "image9":
            case "leash":return img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. 8 8 8 . . . . . . . . . . . 
8 . . . 8 . . . . . . . . . . 
8 . . . 8 . . . . . . . . . . 
. c 8 8 . . . . . . . . . . . 
. . . c 8 . . . . . . . . . . 
. . . . c 8 . . . . . . . . . 
. . . . . c 8 . . . . . . . . 
. . . . . . c 8 8 . . . . . . 
. . . . . . . . c 8 8 . . . . 
. . . . . . . . . . c 8 8 b . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`;
            case "image4":
            case "bone":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . 1 1 1 . . . 
. . . . . . . . . . 1 1 1 . . . 
. . . . . . . . . . 1 1 1 1 1 . 
. . . . . . . . . 1 1 1 1 1 1 . 
. . . . . . . . 1 1 1 1 d b b . 
. . . . . . . 1 1 1 1 d b . . . 
. . . . . . 1 1 1 1 d b . . . . 
. . . . . 1 1 1 1 d b . . . . . 
. . . . 1 1 1 1 d b . . . . . . 
. 1 1 1 1 1 1 d b . . . . . . . 
. 1 1 1 1 1 d b . . . . . . . . 
. 1 d 1 1 d b . . . . . . . . . 
. . d 1 d b . . . . . . . . . . 
. . . b b b . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image13":
            case "Neighbour":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
........b.........................................
.......bb.........................................
.......bb.........................................
......bbb............44444444.....................
.....bb1b..........444444444444...................
.....b1bb........4444444444444444.................
....bb1bb......ee44ff44444444ff44ee...............
....b1bbb......ee444fff4444fff444ee...............
...bb1bbb......ee4444fff44fff4444ee...............
...bbbbbb......ee4444444444444444ee...............
...bbbbbb......ee444661f44661f444ee...............
...bbbbbb.......e444ff6f44ff6f444e................
...bbbbbb.......e444ffff44ffff444e................
...bbbbbb.......e4444444444444444e................
...bbbbbb.......e4444444444444444e................
...bbbbbb.......e4444444444444444e................
...cbbbbb.......ee44444444444444ee................
...cbbbbb........eeeeeeffffeeeeee.................
....cbbbb........eeeeeffeeffeeeee.................
....cbbbb..........eeeeeeeeeeee...................
.....cbbb............44444444.....................
......cbb............11111111.....................
......cbbf........aa88aaaaaa88aa..................
......ffff.....aaaaa88aaaaaa88aaaaa...............
.......fff.....aaaaa88aaaaaa88aaaaa...............
........ff44...aaaaa8888888888aaaaa...............
.........44aa..aaaca8888888888acaaa...............
.........44aaa.aaaca8888888888acaaa...............
...........caaaaacca8888888888a.aaa...............
............caaaac.a8888888888a.aaa...............
.............caaac.a8888888888a.aaa...............
..............cccc.888888888888.aaa...............
...................888888888888.aaa...............
...................888888888888.444...............
...................888888888888...................
...................888888888888...................
.....................888..888.....................
.....................888..888.....................
.....................888..888.....................
...................88888..88888...................
...................88888..88888...................
..................................................
..................................................
`;
            case "image1":
            case "John Weak":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f 2 2 f f f . . . . 
. . . f f f 2 2 2 2 f f f . . . 
. . f f f e e e e e e f f f . . 
. . f f e 2 2 2 2 2 2 e e f . . 
. . f e 2 f f f f f f 2 e f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e e d d d d d d e e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f 2 2 2 2 2 2 f 4 e . . 
. . 4 d f 2 2 2 2 2 2 f d 4 . . 
. . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image7":
            case "Monster":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
